sudo: true
dist: trusty
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

script:
  - composer test

before_install:
  - sudo apt-get update
  - sudo apt-get -y --reinstall install libwebp-dev
  - sudo apt-get -y --reinstall install imagemagick
  - sudo mkdir imagemagick
  - cd imagemagick
  - sudo apt-get build-dep -y imagemagick
  - sudo apt-get install -y libwebp-dev devscripts
  - sudo apt-get source imagemagick
  - cd imagemagick-*
  - sudo debuild -uc -us
  - sudo dpkg -i ../*magick*.deb
  - cd ../..
  - printf "\n" | pecl install imagick-beta
  - composer install
